services:
  - type: web
    name: crm-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci --legacy-peer-deps --include=dev && npm run build:api && npx prisma generate
    startCommand: node dist/apps/api/main.js
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: api/v1
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://crm-delta-jet.vercel.app
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 100
